Update test-step.yml

diff --git a/.github/workflows/test-step.yml b/.github/workflows/test-step.yml
--- a/.github/workflows/test-step.yml
+++ b/.github/workflows/test-step.yml
@@ -13,38 +13,24 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-  
-
-      - name: Check The Domain is Work Or Not 
-        run: |
-         secs=60                         # Set interval (duration) in seconds.
-         endTime=$(( $(date +%s) + secs )) # Calculate end time.
-
-         while [ $(date +%s) -lt $endTime ]; do  # Loop until interval has elapsed.
-           STATUS_CODE=$(curl \
-                      --output /dev/null \
-                      --silent \
-                      --write-out "%{http_code}" \
-                      "https://axim-backend-testing.sandbox-london-b.fetch-ai.com")
-         
-         if (( STATUS_CODE == 200 )); then
-            echo "website is working"
-         else     
-            echo "Website is down some error come! , got  $STATUS_CODE"
-         fi
-         
-         done
-         
-      - uses: actions/checkout@v2
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.9'  
           
-      - name: Run Python script
+      - uses: actions/checkout@v3
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.9'
+
+      - name: Run Python e2e script
         if: ${{ success() }}  
         run: |
+          python -m pip install requests
+            
+          if [[ $? = 0 ]]; then
             echo "script is run successfully"
+          else
+            echo "Script is fail"
+            exit 1;
+          fi
            
       - name: delete hem chart always
         if: ${{ always() }}  
