Update test-step.yml

diff --git a/.github/workflows/test-step.yml b/.github/workflows/test-step.yml
--- a/.github/workflows/test-step.yml
+++ b/.github/workflows/test-step.yml
@@ -18,25 +18,26 @@ jobs:
         id: vars
         run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
           
-      - name: check the Domain is work or not 
-        run: |
-           secs=60                      
-           endTime=$(( $(date +%s) + secs )) # Calculate end time.
+      - name: Wait for 360 seconds
+        uses: jakejarvis/wait-action@master
+        with:
+          time: '60s'
 
-           while [ $(date +%s) -lt $endTime ]; do
-            STATUS_CODE=$(curl \
+      - name: Check The Domain is Work Or Not 
+        run: |
+          STATUS_CODE=$(curl \
                       --output /dev/null \
                       --silent \
                       --write-out "%{http_code}" \
                       "https://axim-backend-testing.sandbox-london-b.fetch-ai.com")
-           done
-      
-           if (( STATUS_CODE == 200 )); then
+        
+          if (( STATUS_CODE == 200 )); then
             echo "website is working"
-           else     
-            echo "Website is down! , got  $STATUS_CODE"
-           fi
-           
+          else     
+            echo "Website is down some error come! , got  $STATUS_CODE"
+            exit 1;
+          fi
+          
       - name: Run Python script
         if: ${{ success() }}  
         run: |
